grocery_app/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from datetime import date, datetime
from grocery_app.models import GroceryStore, GroceryItem, User
from grocery_app.forms import GroceryStoreForm, GroceryItemForm
from grocery_app import app, db
from wtforms import StringField, DateField, SelectField, SubmitField, FloatField, TextAreaField, SignUpForm, LoginForm
from flask.ext.bcrypt import Bcrypt

main = Blueprint("main", __name__)
auth = Blueprint("auth", __name__)

##########################################
#           Routes                       #
##########################################

@main.route('/')
def homepage():
    all_stores = GroceryStore.query.all()
    print(all_stores)
    return render_template('home.html', all_stores=all_stores)

@login_required
@main.route('/new_store', methods=['GET', 'POST'])
def new_store():
    # TODO: Create a GroceryStoreForm
    form = GroceryStoreForm()

    # TODO: If form was submitted and was valid:
    # - create a new GroceryStore object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the store detail page.
    if form.validate_on_submit():
        
        new_store = GroceryStore(
                title=form.title.data,
                address=form.address.data,
                
            )
        db.session.add(new_store)
        db.session.commit()

        flash('New store added')
        return redirect(url_for('main.store_detail', store_id=new_store.id))

    # TODO: Send the form to the template and use it to render the form fields
    return render_template('new_store.html', form=form)

@login_required
@main.route('/new_item', methods=['GET', 'POST'])
def new_item():
    # Creates a GroceryItemForm
    form = GroceryItemForm()
    
    # If form was submitted and was valid:
    # - create a new GroceryItem object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the item detail page.
    
    if form.validate_on_submit():
        
        new_item = GroceryItem(
            name=form.name.data,
            price=form.price.data,
            category=form.category.data,
            photo_url=form.photo_url.data,
            store=form.store.data
        )
        db.session.add(new_item)
        db.session.commit()
        flash('New item added')
        return redirect(url_for('main.item_detail', item_id=new_item.id))
    return render_template('new_item.html', form=form)

@main.route('/store/<store_id>', methods=['GET', 'POST'])
def store_detail(store_id):
    store = GroceryStore.query.get(store_id)
    # Creates a GroceryStoreForm and pass in `obj=store`
    form = GroceryStoreForm(obj=store)

    # If form was submitted and was valid:
    # - update the GroceryStore object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the store detail page.

    if form.validate_on_submit():
        new_store = GroceryStore(
        title = form.data.title,
        address = form.address.data
        )
        db.session.add(new_store)
        db.committ()

        flash("New store was added")
        return redirect(url_for('main.store_detail', store_id=store.id, store=store))
   
    return render_template('store_detail.html', store=store)

@main.route('/item/<item_id>', methods=['GET', 'POST'])
def item_detail(item_id):
    item = GroceryItem.query.get(item_id)
    # Creates a GroceryItemForm and pass in `obj=item`
    form = GroceryItemForm(obj=item)

    # If form was submitted and was valid:
    # - update the GroceryItem object and save it to the database,
    # - flash a success message, and
    # - redirect the user to the item detail page.
    if form.validate_on_submit():
        new_item = GroceryItem(
            name=form.name.data,
            price=form.price.data,
            category=form.category.data,
            photo_url=form.photo_url.data,
            store=form.store.data
        )

        db.session.add(new_item)
        db.session.commit()

        flash('New item created')
        return redirect(url_for('main.item_detail', item_id=new_item.id))

    #  Sends the form to the template and use it to render the form fields
    item = GroceryItem.query.get(item_id)
    return render_template('item_detail.html', item=item)


# sign up form 
@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    print('in signup')
    form = SignUpForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            username=form.username.data,
            password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        flash('Account Created.')
        print('created')
        return redirect(url_for('auth.login'))
    print(form.errors)
    return render_template('signup.html', form=form)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            next_page = request.args.get('next')
            return redirect(next_page if next_page else url_for('main.homepage'))
    return render_template('login.html', form=form)

@login_required
@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.homepage'))

@main.route('/add_to_shopping_list/<item_id>', methods=['POST'])
def add_to_shopping_list(item_id):

    item = User(
            item=item_id
            
        )
    db.session.add(item)
    db.session.commit(item)

@main.route('/shopping_list')
@login_required
def shopping_list():
    item = User.query.filter_by(item)
    print(item)
    return item
    

grocery_app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Grocery Store Tracker</title>
        <link rel="stylesheet" href="/static/style.css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}
            <nav>
                <a href="/">Home</a>
                <div>
                    <a href="/new_store">New Store</a>
                    <a href="/new_item">New Item</a>
                </div>
            </nav>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

grocery_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Grocery Store Tracker</h1>

<p><em>The best place to track prices and find the hottest deals!</em></p>

<h2>All Stores</h2>

{% for store in all_stores %}
<div class="store">
    <a href="/store/{{ store.id }}">{{ store.title }}</a> - 
    {{ store.items|length }} items
    <p><strong>Address:</strong> {{ store.address }}</p>
</div>
{% endfor %}

{% endblock %}

grocery_app/templates/item_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Item - {{ item.name }}</h1>

<p><img src="{{ item.photo_url }}" width="250px" height="250px"></p>

<p><strong>Price:</strong> {{ item.price }}</p>

<p><strong>Category:</strong> {{ item.category }}</p>

<p><strong>Store:</strong> {{ item.store.title }}</p>


<h2>Edit Item</h2>

<form>
    <fieldset>
        <legend>Please enter your information:</legend>



        <!-- Removes the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        <p><em>

            Item: {{item.name}}
            Price: {{item.price}}
            Category: {{item.category}}
            Store: {{item.store.title}}

            </em></p>

        <input type="submit" value="Submit">
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/login.html
<!-- login.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/new_item.html
{% extends 'base.html' %}
{% block content %}

<h1>New Item</h1>

<form action="{{url_for('main.new_item')}}" method="POST">
    {{form.csrf_token}}
    <fieldset>
        <legend>Please enter your information:</legend>



        <!-- Removes the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        
            {{ form.name.label }}
            {{ form.name }}

            {{ form.price.label }}
            {{ form.price }}
            
            {{ form.photo_url.label }}
            {{ form.photo_url }}

            {{form.category.label}}
            {{form.category}}

            {{ form.store.label }}
            {{ form.store }}

            {{ form.submit }}
    </fieldset>
</form>


{% endblock %}

grocery_app/templates/new_store.html
{% extends 'base.html' %}
{% block content %}

<h1>New Store</h1>

<form action="{{url_for('main.new_store')}}" method="POST">
    {{form.csrf_token}}
    <fieldset>
        <legend>Please enter your information:</legend>



        <!-- Removes the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        

        {{ form.title.label }}
        {{ form.title }}
        {{ form.address.label }}
        {{ form.address }}

        {{form.submit}}
            
        

       
    </fieldset>
</form>


{% endblock %}

grocery_app/templates/signup.html
<!-- signup.html -->
{% extends 'base.html' %}
{% block content %}

<h1>Log In</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }}
        {{ form.username }}
        <ul>
        {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.password.label }}
        {{ form.password }}
        <ul>
        {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
        {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

grocery_app/templates/store_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Store - {{ store.title }}</h1>

<strong>Address:</strong> {{ store.address }}

<h2>Items</h2>

<div class="items">
    {% for item in store.items %}
    <div class="item-details">
        <a href="/item/{{ item.id }}"><img src="{{ item.photo_url }}" alt="{{ item.name }}" width="200px">
        <p><strong>{{ item.name }}</strong></p></a>
        <p><strong>Price: ${{ item.price }}</strong></p>
    </div>
    {% endfor %}
</div>


<h2>Edit Store</h2>

<form>
    <fieldset>
        <legend>Please enter your information:</legend>



        <!-- Removes the next paragraph and use the `form` object passed in 
            from the route to render a form. -->
        <p><em>

            {{store.title}}
            {{store.address}}
        </em></p>

        
    </fieldset>
</form>

{% endblock %}